@port = 3000
@hostname = localhost
@api =  http://{{hostname}}:{{port}}

GET {{api}}/

### ----------- CATS ----------- ###

### index
GET {{api}}/cats

### index - query
GET {{api}}/cats?name=cat-name&age=99734

### show
GET {{api}}/cats/77

### create
POST {{api}}/cats
Content-Type: application/json

{
    "age": 2599,
    "name": "catty",
    "breed": "argon"
}

### update
PUT {{api}}/cats/1

Content-Type: application/json

{
    "name": "catty",
    "age": 2,
    "breed": "origon"
}


### ------- AUTH -------- ####

POST {{api}}/auth/login
Content-Type: application/json

{
    "username": "maria",
    "password": "guess"
}