@port = 3000
@hostname = localhost
@api =  http://{{hostname}}:{{port}}

GET {{api}}/

### ----------- CATS ----------- ###

### index
GET {{api}}/cats

### index - query
GET {{api}}/cats?name=cat-name&age=99734

### show
GET {{api}}/cats/77

### create
POST {{api}}/cats
Content-Type: application/json

{
    "age": 2599,
    "name": "catty",
    "breed": "argon"
}

### update
PUT {{api}}/cats/1

Content-Type: application/json

{
    "name": "catty",
    "age": 2,
    "breed": "origon"
}


### ------- AUTH -------- ####

POST {{api}}/auth/login
Content-Type: application/json

{
    "username": "maria",
    "password": "guess"
}

###

GET {{api}}/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoibWFyaWEiLCJpYXQiOjE3NzQ0MDAxODksImV4cCI6MTc3NDQwMDIxOX0.WCCULnG1HOyVuKjcmrZt6WFdgjxoVCA0Ly8aURtqBAA

Content-Type: application/json
